# Generated by Django 4.2.10 on 2024-02-12 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutlineServer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("url", models.CharField(max_length=255)),
                ("port", models.IntegerField()),
                ("api_url", models.CharField(max_length=255)),
                ("api_cert", models.CharField(max_length=255)),
                ("keys_per_user", models.IntegerField()),
                ("max_data_per_key", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OutlineServerKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("key_id", models.CharField(max_length=255)),
                ("key", models.CharField(max_length=255)),
                ("data_limit", models.BigIntegerField()),
                ("data_used", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="keys", to="servers.outlineserver"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="keys", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
