# Generated by Django 4.2.10 on 2024-02-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlineserver",
            name="country",
            field=models.CharField(default="Russia", max_length=100),
            preserve_default=False,
        ),
    ]
