# Generated by Django 4.2.10 on 2024-02-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0003_alter_outlineserver_keys_per_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outlineserver",
            name="url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="outlineserverkey",
            name="key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="outlineserverkey",
            name="key_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
    ]
