# Generated by Django 4.2.10 on 2025-08-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0004_alter_outlineserver_url_alter_outlineserverkey_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outlineserverkey",
            name="data_limit",
            field=models.BigIntegerField(
                default=0, help_text="Use 0 for unlimited data", verbose_name="Data limit (MB)"
            ),
        ),
        migrations.AlterField(
            model_name="outlineserverkey",
            name="name",
            field=models.CharField(help_text="Up to 100 characters long", max_length=100, verbose_name="Key name"),
        ),
    ]
