# Generated by Django 4.2.10 on 2025-08-09 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarzbanServer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("country", models.CharField(max_length=100)),
                ("url", models.CharField(blank=True, default="", max_length=255)),
                ("port", models.IntegerField(default=0)),
                ("api_url", models.CharField(max_length=255)),
                ("api_token", models.CharField(max_length=255)),
                ("keys_per_user", models.IntegerField(default=0)),
                ("max_data_per_key", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MarzbanServerKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Up to 100 characters long", max_length=100, verbose_name="Key name"),
                ),
                ("config_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("config", models.CharField(blank=True, default="", max_length=2000)),
                (
                    "data_limit",
                    models.BigIntegerField(
                        default=0, help_text="Use 0 for unlimited data", verbose_name="Data limit (MB)"
                    ),
                ),
                ("data_used", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="servers_marzban.marzbanserver",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marzban_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
