# Generated by Django 4.2.10 on 2025-08-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers_marzban", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marzbanserver",
            old_name="api_token",
            new_name="api_password",
        ),
        migrations.AddField(
            model_name="marzbanserver",
            name="api_user",
            field=models.CharField(default=" ", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marzbanserver",
            name="vless_inbound",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="marzbanserverkey",
            name="key_id",
            field=models.UUIDField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
